"""empty message

Revision ID: 056ebc60a9f2
Revises: 85d9b7adadf6
Create Date: 2018-12-30 22:29:22.751981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056ebc60a9f2'
down_revision = '85d9b7adadf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_column('user', 'display_name')
    # ### end Alembic commands ###